# Generated by Django 5.1.1 on 2024-10-21 06:52

import course.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('domain_img', models.ImageField(upload_to=course.models.getFileName)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(blank=True, max_length=40)),
                ('profile_img', models.CharField(blank=True, null=True, max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.TextField(default='course description', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_duration',
            field=models.CharField(default='1month', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_thumbnail',
            field=models.ImageField(default='img_url', upload_to=course.models.getFileName),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='visibility',
            field=models.BooleanField(default=False, help_text='Tick - Locked, Untick - Unlocked'),
        ),
        migrations.AddField(
            model_name='course',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.domain'),
            preserve_default=False,
        ),
    ]
