# Generated by Django 5.1.1 on 2024-10-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_domain_user_course_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_cost',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
