# Generated by Django 5.1.1 on 2024-10-24 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_course_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='domain_img',
        ),
    ]
