# Generated by Django 5.1.1 on 2024-10-25 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_domain_domain_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='checkpoint_title',
            field=models.CharField(default='check points', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='8hrs', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='technology_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
