# Generated by Django 5.1.1 on 2024-10-25 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_checkpoint_title_course_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='checkpoint_description',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='duration',
            new_name='checkpoint_duration',
        ),
    ]
