# Generated by Django 5.1.1 on 2024-10-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_rename_description_course_checkpoint_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_skills',
            field=models.CharField(default='skill 1,skill 2,skill 3,skill 4', max_length=3000),
            preserve_default=False,
        ),
    ]
