# Generated by Django 5.1.2 on 2024-10-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
