# Generated by Django 5.1.2 on 2024-10-27 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_studentuser_delete_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentUser',
            new_name='Student',
        ),
    ]
