# Generated by Django 5.1.2 on 2024-10-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_rename_studentuser_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='checkpoint_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='checkpoint_duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='checkpoint_title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='technology_used',
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='checkpoint_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='checkpoint_duration',
            field=models.CharField(default='8 hrs', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='checkpoint_title',
            field=models.CharField(default='chck poitn title', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='technology_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='checkpoint_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
