<<<<<<< Updated upstream
# Generated by Django 5.1.2 on 2024-10-31 11:58
=======
# Generated by Django 5.1.2 on 2025-01-02 08:19
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_remove_course_checkpoint_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpoint',
            name='checkpoint_description',
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='checkpoint_duration',
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='checkpoint_title',
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='technology_used',
        ),
        migrations.RemoveField(
            model_name='course',
            name='checkpoint_no',
        ),
        migrations.AddField(
            model_name='course',
            name='checkpoint_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='checkpoint_duration',
<<<<<<< Updated upstream
            field=models.CharField(default='check point duration', max_length=30),
=======
            field=models.CharField(default='-', max_length=30),
>>>>>>> Stashed changes
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='checkpoint_title',
<<<<<<< Updated upstream
            field=models.CharField(default='check point title', max_length=255),
=======
            field=models.CharField(default='CheckPoint Title', max_length=255),
>>>>>>> Stashed changes
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='technology_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
