# Generated by Django 5.1.2 on 2024-11-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
