# Generated by Django 5.1.2 on 2024-11-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_enrollment_progress_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='checkpoint_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='checkpoint_duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='checkpoint_title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='technology_used',
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='checkpoint_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='checkpoint_duration',
            field=models.CharField(default='2 hrs', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='checkpoint_title',
            field=models.CharField(default='CheckPoints', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='technology_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
