# Generated by Django 5.1.2 on 2024-11-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_remove_course_checkpoint_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='checkpoint_description',
            field=models.TextField(blank=True, default='Default Checkpoint Description', null=True),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='checkpoint_duration',
            field=models.CharField(default='1 hour', max_length=30),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='checkpoint_title',
            field=models.CharField(default='Default Checkpoint Title', max_length=255),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='technology_used',
            field=models.CharField(blank=True, default='Not specified', max_length=100, null=True),
        ),
    ]
