# Generated by Django 5.1.2 on 2024-11-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_student_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title of the notification, e.g., 'New Course Available'", max_length=255)),
                ('message', models.TextField(help_text='Detailed message content of the notification')),
                ('type', models.CharField(choices=[('course', 'New Course'), ('message', 'Message'), ('payment', 'Payment Update'), ('other', 'Other')], default='other', help_text='Type of notification for categorization', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the notification was created')),
                ('extra_data', models.JSONField(blank=True, help_text='JSON field for any additional information like links, passcodes, or metadata', null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
