# Generated by Django 5.1.2 on 2024-12-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='visibility',
            new_name='lock',
        ),
        migrations.AlterField(
            model_name='notification',
            name='extra_data',
            field=models.JSONField(blank=True, help_text=' additional information like {links: , passcodes: , or metadata: }', null=True),
        ),
    ]
