# Generated by Django 5.1.2 on 2025-01-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_alter_course_course_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='technology_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
