# Generated by Django 5.1.2 on 2025-01-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_alter_student_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_thumbnail',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
