# Generated by Django 5.1.2 on 2025-01-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0027_alter_course_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='slug_default'),
            preserve_default=False,
        ),
    ]
